---
abstract: 'Make payments using Nets'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-NetsPayment
no_index:
  directory:
    - t
    - inc
requires:
  EV: 4.17
  IO::Socket::IP: 0.29
  IO::Socket::SSL: 1.981
  Net::SSLeay: 1.58
  URI::_punycode: 0.04
  common::sense: 3.73
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-netspayment/issues
  homepage: https://metacpan.org/release/Mojolicious-Plugin-NetsPayment
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jhthorsen/mojolicious-plugin-netspayment.git
version: 0.01
